export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';


export const FETCH_ME = 'FETCH_ME';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_MY_SAVED_SNIPPETS = 'FETCH_MY_SAVED_SNIPPETS';
export const FETCH_USER_SAVED_SNIPPETS = 'FETCH_USER_SAVED_SNIPPETS';
export const FETCH_MY_CREATED_SNIPPETS = 'FETCH_MY_CREATED_SNIPPETS';
export const FETCH_USER_CREATED_SNIPPETS = 'FETCH_USER_CREATED_SNIPPETS';


export const CREATE_SNIPPET = 'CREATE_SNIPPET';
export const FETCH_SNIPPET = 'FETCH_SNIPPET';
export const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';
export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const UPVOTE_SNIPPET = 'UPVOTE_SNIPPET';
export const DOWNVOTE_SNIPPET = 'DOWNVOTE_SNIPPET';
export const SAVE_SNIPPET = 'SAVE_SNIPPET';


export const CREATE_COMMENT = 'CREATE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_MOST_VIEWS = 'FETCH_MOST_VIEWS';
export const FETCH_MOST_UPVOTES = 'FETCH_MOST_UPVOTES';
export const FETCH_MOST_SAVED = 'FETCH_MOST_SAVED';


export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';


export const FETCH_ALL_LANGUAGES = 'FETCH_ALL_LANGUAGES';
