

// Used to map to appropriate mode for usage with react ace
export const languagesMap = {
    "assembly x86": "assembly_x86",
    "c": "c_cpp",
    "c++": "c_cpp",
    "coffeescript": "coffee",
    "c#": "csharp",
    "css": "css",
    "dockerfile": "dockerfile",
    "ejs": "ejs",
    "fortran": "fortran",
    "go": "golang",
    "html": "html",
    "html exixir": "html_elixir",
    "html ruby": "html_ruby",
    "haskell": "haskell",
    "java": "java",
    "javascript": "javascript",
    "json": "json",
    "jsx": "json",
    "julia": "julia",
    "reactjs": "jsx",
    "reactnative": "jsx",
    "latex": "latex",
    "less": "less",
    "lua": "lua",
    "makefile": "makefile",
    "matlab": "matlab",
    "mysql": "mysql",
    "objectivec": "objectivec",
    "ocaml": "ocaml",
    "pascal": "pascal",
    "php": "php",
    "plain text": "plain_text",
    "powershell": "powershell",
    "python": "python",
    "r": "r",
    "ruby": "ruby",
    "sass": "sass",
    "scala": "scala",
    "scss": "scss",
    "sql": "sql",
    "swift": "swift",
    "typescript": "typescript",
    "verilog": "verilog",
    "xml": "xml",
    "yaml": "yaml"
};


export const supportedLanguages = [
    "Assembly x86",
    "C",
    "C++",
    "CoffeeScript",
    "C#",
    "CSS",
    "Dockerfile",
    "EJS",
    "Fortran",
    "Go",
    "HTML",
    "HTML Exixir",
    "HTML Ruby",
    "Haskell",
    "Java",
    "JavaScript",
    "JSON",
    "JSX",
    "Julia",
    "ReactJS",
    "ReactNative",
    "LaTex",
    "LESS",
    "Lua",
    "Makefile",
    "Matlab",
    "MySQL",
    "ObjectiveC",
    "OCaml",
    "Pascal",
    "PHP",
    "Plain Text",
    "PowerShell",
    "Python",
    "R",
    "Ruby",
    "SASS",
    "Scala",
    "SCSS",
    "SQL",
    "Swift",
    "TypeScript",
    "Verilog",
    "XML",
    "Yaml"
];